# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ONyRkKuLWYAc0N5lnnAsVY8jqLwaYZZb
"""

import pandas as pd

df_attendance = pd.read_csv('attendance.csv')

df_groups = pd.read_csv('STUDENT_GROUP.csv')

df_attendance.head(3)

df_attendance.tail(3)

df_attendance.dtypes

df_groups.dtypes

df_attendance.rename(columns={'STUDENT_ID':'student_id'}, inplace=True)

df_attendance.head(3)

df_attendance=df_attendance.rename(columns={'STUDENT_ID':'student_id'})

df_groups.describe()

df_attendance.describe()

import pandas as pd
df_attendance['student_id']=pd.to_numeric(df_attendance['student_id'],errors='coerce')

df_attendance.dropna(subset=['student_id'],inplace=True)

df_attendance['student_id'] = df_attendance['student_id'].astype('int64')

df_attendance.describe()

import pandas as pd

merged_df = pd.merge(df_attendance, df_groups, on='student_id', how='inner')

filtered_df = merged_df[merged_df['student_id'].notna()]

filtered_df[['DT', 'group_id']]